# Generated by Django 5.1.4 on 2025-01-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='quantidade_livros',
        ),
    ]
