# Generated by Django 5.1.4 on 2025-01-31 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_autor_quantidade_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
