# Generated by Django 5.1.4 on 2025-02-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_de_patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='estado',
        ),
    ]
