# Generated by Django 5.1.4 on 2025-02-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_de_patrimonio', '0002_remove_fornecedor_cep_remove_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='bens',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='bens',
            old_name='fornecedor_id',
            new_name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='bens',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='inicio_contrato',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_movimentacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('bem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_de_patrimonio.bens')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_de_patrimonio.bens')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_gestao_de_patrimonio.setores')),
            ],
        ),
        migrations.AddField(
            model_name='bens',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_gestao_de_patrimonio.setores'),
        ),
    ]
